export const U_PROX_API_URL = 'U_PROX_API_URL';
export const U_PROX_API_USER = 'U_PROX_API_USER';
export const U_PROX_API_PASS = 'U_PROX_API_PASS';
export const U_PROX_API_PASS_HASH_PHRASE = 'U_PROX_API_PASS_HASH_PHRASE';
export const U_PROX_API_LOGIN_INTERVAL = 'U_PROX_API_LOGIN_INTERVAL';
